# Generated by Django 4.0.1 on 2022-03-07 15:41

import connect1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=connect1.models.filepath)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('phoneno', models.BigIntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('toaddpost', models.ImageField(blank=True, null=True, upload_to=connect1.models.filepath)),
                ('posts', models.JSONField(default=dict)),
                ('connections', models.JSONField(default=dict)),
                ('connectionrequests', models.JSONField(default=dict)),
                ('pendingconnections', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='userverify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=300)),
            ],
        ),
    ]
