# Generated by Django 3.2.6 on 2021-12-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.CharField(default='el', max_length=30),
        ),
    ]
