# Generated by Django 3.2.6 on 2021-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect1', '0002_auto_20211203_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.JSONField(default=dict),
        ),
    ]
