# Generated by Django 3.2.6 on 2021-11-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect1', '0003_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phoneno',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
