# Generated by Django 3.2.6 on 2021-12-03 15:11

import connect1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect1', '0003_auto_20211203_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='toaddpost',
            field=models.ImageField(blank=True, null=True, upload_to=connect1.models.filepath),
        ),
    ]
